Home work 01
MrNeelixs/Free_IT-Roman_course- pull request #1
Opened 2021-02-14 12:04 UTC by MrNeelixs

Method implementation Main (System.out.println)

2021-02-18 13:04 UTC, NadezhdaPenkrat reviewed
привет! исполнение заданий Lesson1 просматриваю и 
выглядит очень сложно- красивым решением:
запустить в среде  idea код получилось , но увы с ошибкой
Error:(28, 5) java: class, interface, or enum expected
вложенности внутренних подклассов в основной в консоль не вывело
(интересно пояснение исполнения : 
понимаю написание кода , запись )

2021-02-19 08:00 UTC, RomanKashenok requested changes
Сделай пожалуйста по классу на задание. И Указывай условие в начале класса в комментарии. ПОка они не сложные я догадываюсь что ты решаешь, но скоро перестану )

2021-02-19 08:00 UTC, RomanKashenok commented on src/main/java/lesson_1/Solution.java
> +        System.out.println(formattedDoubleSeconds + " секунд" + " это " + formattedDoubleMinutes + " минут" + " или " + hours + " часа" + " или " + formattedDoubleDay + " дня" + " или " + formattedDo
1. По итогу хотелось бы получить что-то человекочитаемое. Если спросят "сколько осталось до нового года", ожидат услышать 3 дня 5 часов 21 минута и 16 секунд, а не 3,232134235 дней
2. убери все double
3. переменные можно инициализировать в момент объявления (по кранйей мере в этой задаче)
4. деление на 604800 вот вообще не очевидно. По сути ты тут сам себе калькулятор (если считать месяца и года, то число для деления будет вообще страшное)

2021-02-19 08:00 UTC, RomanKashenok commented on src/main/java/lesson_1/Solution.java
> +        System.out.printf("Введено => %s;%nРеверс => %s.\n", inputNumber, new StringBuilder(inputNumber).reverse().toString());
Суть тут была не найти решение на просторах интернета, а вычленить все цифры и составить число в обратном порядке :)

2021-02-19 08:00 UTC, RomanKashenok commented on src/main/java/lesson_1/Solution.java
> +        System.out.println(inputNumber.chars().distinct().count() == 4 ? "В даном числе все цифры разные" : "В даном числе есть одинаковые цыфры.");
решение огонь, но сильно читерское для 1го занятия :)

2021-02-24 18:24 UTC, merged